name: Run Subfinder

on:
  workflow_dispatch: # Allows manually triggering the workflow
    inputs:
      domain:
        description: 'Domain name to scan'
        required: true
        default: 'hackerone.com'

jobs:
  subfinder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Subfinder
      run: |
        curl -LO https://github.com/projectdiscovery/subfinder/releases/latest/download/subfinder-linux-amd64.tar.gz
        tar -xzvf subfinder-linux-amd64.tar.gz
        sudo mv subfinder /usr/local/bin/

    - name: Run Subfinder
      run: |
        subfinder -d ${{ github.event.inputs.domain }} > subdomains.txt
        cat subdomains.txt

    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: subfinder-results
        path: subdomains.txt
